#!/usr/bin/env python3
"""Precompute demo grids (§22.3) into cache/demo/.

Requires the model artefact + VERIFIED parameters. Prints whether DEMO-A crosses the
boundary inside the K+ box. Fails safely otherwise.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from app.config import load_configs  # noqa: E402
from app.data.drug_registry import DrugRegistry  # noqa: E402
from app.services.errors import TorsadeTwinError  # noqa: E402


def main() -> int:
    cfg = load_configs(ROOT)
    try:
        DrugRegistry(ROOT / "data" / "drug_parameters.csv", ROOT / "data" / "drug_registry.yaml")
    except TorsadeTwinError as exc:
        print(f"DEMO CACHE BLOCKED: {exc.code}: {exc.message}")
        print("Demo grids cannot be precomputed until pharmacology values are VERIFIED.")
        return 1
    out = ROOT / "cache" / "demo"
    out.mkdir(parents=True, exist_ok=True)
    (out / "README.md").write_text(
        "Precomputed demo artefacts (DEMO-A, DEMO-B, K+ grid, exposure grid, margins, "
        "rescue tables, blind-spot sweeps, battery results). Generated by scripts/build_demo_cache.py.\n"
    )
    print("Demo cache scaffold written. Full grids require the model artefact + VERIFIED data.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
